webtalk_init -webtalk_dir C:/Users/me705924/projet/projet.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 10 17:52:42 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174552755_1777500891_210749928_468" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d42d6cf3-c5ef-467c-bceb-347cac8ea95d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a68c4856d4494ca6b396c6d44cc27661" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "44" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "31 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9020_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1563847507 -regid "174552755_1777500891_210749928_468" -xml C:/Users/me705924/projet/projet.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/me705924/projet/projet.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/me705924/projet/projet.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
